development:
  HTTP_USER: john
  HTTP_PASSWORD: doe
  GMAIL_USERNAME: johndoe@gmail.com
  GMAIL_PASSWORD: password

production:
  HTTP_USER: john
  HTTP_PASSWORD: doe
  GMAIL_USERNAME: johndoe@gmail.com
  GMAIL_PASSWORD: password
  TWITTER_CONSUMER_KEY: key
  TWITTER_CONSUMER_SECRET: secret
  TWITTER_ACCESS_TOKEN: token
  TWITTER_ACCESS_TOKEN_SECRET: token_secret